"""empty message

Revision ID: 79b3081c924c
Revises: f514f5a8298e
Create Date: 2026-02-01 14:19:29.856883

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79b3081c924c'
down_revision: Union[str, Sequence[str], None] = 'f514f5a8298e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_persons_tg_id'), 'persons', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_tg_id'), table_name='persons')
    op.drop_column('persons', 'tg_id')
    # ### end Alembic commands ###
